### ISSUE TITLE
the latest Windows bootstrap idiosyncrasies

### ISSUE THREAD

**Issue by jstange** [cloudamatic/mu#102]
- Initial knife bootstrap appears to hang forever. If you RDP into an in-progress node exhibiting this behavior, you'll see a ruby.exe process associated with a Chef run, sitting idle. If you kill it, subsequent bootstrap calls seem to proceed normally. It's unclear if this process is one that we're initiating as part of bootstrapping, or coming from somewhere else (inherited from the AMI, for example).

- Windows nodes still routinely get wedged in the middle of a reboot, sometimes badly enough for AutoScale to terminate them. This behavior is nondeterministic. All of our Mu-side "connect and do something" loops for Windows have some logic to force reboots along when they suspect this condition. It can, however, occur when MommaCat isn't actively involved, e.g. when userdata reboots to apply updates, and so there's nobody to jump in and save the node from itself. We may have to have a general-purpose `isWindowsHosed?` method that prods Mu-tagged Windows machines with both RDP and  WinRM, and if nothing answers for an extended period of time gives them a kick in the ribs.

- Current builds eventually reach a state where `--no-fips` is required to run normally:
```
Jan 11 13:34:56 - groomers/chef - chef-client.bat : C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-config-12.21.14/lib/chef-config/config.rb:1084:in `fips_mode=': Turning on FIPS mode failed: fingerprint does not match (OpenSSL::OpenSSLError)
    + CategoryInfo          : NotSpecified: (C:/opscode/chef...::OpenSSLError):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Cursory research suggests that this may be an OpenSSL library problem.

**Comment by ryantiger658** [comment]
The node is running chef-client 12.21.14. on version 12.19.33 they noted a change to the FIPS system. Perhaps that is related. 

https://github.com/chef/chef/blob/master/CHANGELOG.md#v121933-2017-02-16

**Comment by jstange** [comment]
I've temporarily added `--no-fips` to Chef runs invoked on Windows nodes from `mu-node-manage`, until this is properly diagnosed and addressed. I'd prefer the Chef FIPS functionality, whatever it does, to actually work.

**Comment by jstange** [comment]
I have a theory about our mysterious stuck `chef-client` process. Strewn throughout the code are scheduled tasks to kick off various things that Windows is weird about running directly. I **think** that's one of them, and I think it might be triggering on boots. I just saw this occur on an older machine, not a new bootstrap.

This might be peculiar to FEMA DMSE, as in something in that project'scookbooks, rather than a Mu at large.

**Comment by jstange** [comment]
Can confirm the stuck `chef-client` was a useless scheduled task. Expunged in development.

Further, unrelated stupidity uncovered: 

- On some images, the WinRM service doesn't begin to work until after a reboot.
