### ISSUE TITLE
Various errors running /opt/mu/lib/test/smoke_test.rb

### ISSUE THREAD

**Issue by cgswong** [cloudamatic/mu#39]
I installed Mu master (via CFN template) in another account with the short-form instance ID successfully. However, upon running `/opt/mu/lib/test/smoke_test.rb` I'm getting various errors:
```
deploying /opt/mu/lib/demo/simple-server-php.yaml and sending output to /root/simple-server-php.out
deploying /opt/mu/lib/demo/simple-server-rails.yaml and sending output to /root/simple-server-rails.out
deploying /opt/mu/lib/demo/simple-server.yaml and sending output to /root/simple-server.out
error deploying /opt/mu/lib/demo/simple-server.yaml. See /root/simple-server.out for details
error deploying /opt/mu/lib/demo/simple-server-php.yaml. See /root/simple-server-php.out for details
error deploying /opt/mu/lib/demo/simple-server-rails.yaml. See /root/simple-server-rails.out for details
0 successes, 3 failures
```

From `/root/simple-server.out`:
```
  "thread": 25114940,
  "name": "firewall_rule_admin_create",
  "details": [
    "/opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'",
    "/opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.26/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'",
    "/opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/plugins/response_target.rb:21:in `call'",
    "/opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/request.rb:70:in `send_request'",
    "/opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.26/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'",
    "/opt/mu/lib/modules/mu/clouds/aws.rb:354:in `call'",
    "/opt/mu/lib/modules/mu/clouds/aws.rb:354:in `method_missing'",
    "/opt/mu/lib/modules/mu/clouds/aws/firewall_rule.rb:63:in `create'",
    "/opt/mu/lib/modules/mu/cloud.rb:919:in `call'",
    "/opt/mu/lib/modules/mu/cloud.rb:919:in `block (4 levels) in <class:Cloud>'",
    "/opt/mu/lib/modules/mu/deploy.rb:440:in `call'",
    "/opt/mu/lib/modules/mu/deploy.rb:440:in `block (2 levels) in createResources'"
  ]
...
  "thread": 9212720,
  "name": "main_thread",
  "details": [
    "/opt/mu/lib/modules/mu/mommacat.rb:1693:in `getpwnam'",
    "/opt/mu/lib/modules/mu/mommacat.rb:1693:in `block in syncMonitoringConfig'"
  ]
}
...
/opt/mu/lib/modules/mu/mommacat.rb:1693:in `getpwnam': can't find user for nagios (ArgumentError)
        from /opt/mu/lib/modules/mu/mommacat.rb:1693:in `block in syncMonitoringConfig'
```

From `/root/simple-server-php.out` (the PHP server is accessible) and `/root/simple-server-rails.out` there are various Chef warnings but the error of interest is likely:
```
/opt/mu/lib/modules/mu/mommacat.rb:1693:in `getpwnam': can't find user for nagios (ArgumentError)
        from /opt/mu/lib/modules/mu/mommacat.rb:1693:in `block in syncMonitoringConfig'
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

I've not attempted to create my own deployment (will do that shortly) but wanted to know if these errors expected or if something was missing.

Thanks.

**Comment by jstange** [comment]
Looks like the Mu master installation failed outright (it'd be nice if the CloudFormation build would tell you that, wouldn't it?).

I've reproduced this and isolated it to an issue with the nokogiri gem and the latest versions of Chef. Committed a Gemfile with a fixed version of nokogiri, and I get clean builds now. Give it a whirl and let us know?

**Comment by cgswong** [comment]
@jstange Did a fresh pull, used AMI ID, ami-e5db3285,for CentOS 6, things looked good again, but now I'm getting:

```
[root@mu-master ~]# /opt/mu/lib/test/smoke_test.rb
deploying /opt/mu/lib/demo/simple-server-php.yaml and sending output to /root/simple-server-php.out
deploying /opt/mu/lib/demo/simple-server.yaml and sending output to /root/simple-server.out
deploying /opt/mu/lib/demo/simple-server-rails.yaml and sending output to /root/simple-server-rails.out
/opt/mu/lib/test/smoke_test.rb:30:in `test': undefined method `scan' for nil:NilClass (NoMethodError)
	from /opt/mu/lib/test/smoke_test.rb:56:in `block (2 levels) in main'
```

**Comment by jstange** [comment]
@zr2d2, can you have a look at the above? Runs clean for me, for what it's worth.

**Comment by zr2d2** [comment]
Is the deployment successful of simple-server-php? I'm guessing it isn't, and that means the grep on that line is unsuccessful. What does /root/simple-server-php.out say?

**Comment by rpattcorner** [comment]
I've installed a master from scratch using the CFN technique and ami-b3e2c7d9 and deployed simple-server-php as well as the smoke test without incident.

Which leads me to wonder if we're looking at a difference between the base AMI in @cgswong 's use case and the one I used.  @cgswong , could you let us know what AMI you're using to build the master (if public) and alternately, try our public ami-b3e2c7d9?

If your ami is private, and you want us to try it, you can share with account in this [one time link](https://onetimesecret.com/secret/n9m1byjw12rnb6dkwleosgafauriysw)

**Comment by rpattcorner** [comment]
Ooops, see you used ami-e5db3285.  I'll test with it.  Meantime try ours ...

**Comment by rpattcorner** [comment]
So ... ami-e5db3285 isn't public ... if you can share per above I can test.  Meanwhile try ours

**Comment by cgswong** [comment]
@rpattcorner The AMI I used, ami-e5db3285, is from the repo in `modules/mu/defaults/amazon_images.yaml`. I don't see the one you provided, ami-b3e2c7d9, in the repo but will give it try since it's public on AWS.

**Comment by rpattcorner** [comment]
Interesting ... wonder if it's related to running in us-west-2, which is where that AMI is.  Will have a look, also will have a look at the current us-east-1 AMI which is ami-127d7d78

**Comment by rpattcorner** [comment]
us-east succeded from template image; us-west-2 failed.  Opened a ticket, researching.

**Comment by cgswong** [comment]
When I tried with `ami-127d7d78` I got an error (didn't save but can always go back and retry again if needed), but when I tried with the AMI you provided, `ami-b3e2c7d9` things were successful (I got an error concerning max VPCs for 2/3 test but at least that's something on my end that can easily be resolved). Both were in us-east-1.

Once I raise my VPC limit I'm going to try again and things should work at which point I'd close this issue unless you want to keep it open for the discrepancy with the images and us-west-2 vs us-east-1.

**Comment by cgswong** [comment]
Raised the VPC limit and all tests passed:

```
[root@mu-master ~]# /opt/mu/lib/test/smoke_test.rb
deploying /opt/mu/lib/demo/simple-server-php.yaml and sending output to /root/simple-server-php.out
deploying /opt/mu/lib/demo/simple-server-rails.yaml and sending output to /root/simple-server-rails.out
deploying /opt/mu/lib/demo/simple-server.yaml and sending output to /root/simple-server.out
Deployment of /opt/mu/lib/demo/simple-server-php.yaml as DEMO-DEV-2016032513-ST was successful, tore down DEMO-DEV-2016032513-ST
Deployment of /opt/mu/lib/demo/simple-server.yaml as DEMO-DEV-2016032513-GE was successful, tore down DEMO-DEV-2016032513-GE
Deployment of /opt/mu/lib/demo/simple-server-rails.yaml as DEMO-DEV-2016032513-NK was successful, tore down DEMO-DEV-2016032513-NK
3 successes, 0 failures
```

Although the other AMI didn't work I feel okay with closing this ticket since I got through the original issue and am okay for now.
