### ISSUE TITLE
Unsuccessful installation in us-west-2 (Oregon) region

### ISSUE THREAD

**Issue by cgswong** [cloudamatic/mu#41]
Referencing issue #39, I've tried a few different AMI (ami-e5db3285, ami-93bea4f2) but each results in the CFN completing but the actual Mu Master not being brought online completely and the smoke test failing with:

```
deploying /opt/mu/lib/demo/simple-server-php.yaml and sending output to /root/simple-server-php.out
deploying /opt/mu/lib/demo/simple-server-rails.yaml and sending output to /root/simple-server-rails.out
deploying /opt/mu/lib/demo/simple-server.yaml and sending output to /root/simple-server.out
/opt/mu/lib/test/smoke_test.rb:30:in `test': undefined method `scan' for nil:NilClass (NoMethodError)
	from /opt/mu/lib/test/smoke_test.rb:56:in `block (2 levels) in main'
```

Is there any update on the us-west-2 region failures? I'm forced to use us-west-2 due to lack of EFS available in other regions.

**Comment by rpattcorner** [comment]
Escalating this ticket ...

**Comment by jstange** [comment]
This is some brain-damage hardwired into the userdata in this CloudFormation template. It's explicitly setting EC2_REGION to us-east-1, which breaks all kinds of things. 

I'm testing a fixed version that uses the appropriate CloudFormation pseudo-parameter.

**Comment by jstange** [comment]
Works for me with the bugfix commit I just dropped into master (c82870c). I also removed a couple of unnecessary *ami-id* arguments in demo kittens that would have fouled tests outside of us-east.

eGT folks: I have a number of suggested improvements for this CloudFormation business. Logged an internal JIRA issue for them.

**Comment by jstange** [comment]
And if you get a minute, @zr2d2 or someone else who does a lot of Ubuntu testing, we should update our list of standard images. We're using some pretty old stuff by default, I think.

**Comment by cgswong** [comment]
Apologies for the delay. I am closing this as I successfully did a manual install on a new CentOS 6 AMI. The CentOS 7 install fails but not an issue for me right now given the 6 install, should maybe open a new issue to troubleshoot further and fix.
