### ISSUE TITLE
mu-node-manage -l throwing a NoSuchMethodError

### ISSUE THREAD

**Issue by rajivkadayam** [cloudamatic/mu#45]
Any ideas what might be causing this problem ? This is on stange-mu.egt-labs.com

[rajiv.kadayam@stange-mu ~]$ mu-node-manage -l
/opt/mu/lib/modules/mu/master.rb:205:in `listUsers': undefined method`[]' for nil:NilClass (NoMethodError)
        from /opt/mu/lib/modules/mu.rb:335:in `userEmail'
        from /opt/mu/lib/modules/mu/config.rb:3262:in`class:Config'
        from /opt/mu/lib/modules/mu/config.rb:26:in `<module:MU>'
        from /opt/mu/lib/modules/mu/config.rb:23:in`<top (required)>'
        from /opt/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /opt/mu/lib/modules/mu.rb:418:in `<module:MU>'
        from /opt/mu/lib/modules/mu.rb:49:in`<top (required)>'
        from /opt/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /opt/mu/bin/mu-node-manage:19:in `<main>'

**Comment by zr2d2** [comment]
The technical answer is because ```$MU_CFG``` is nil on line 205. That line logs a message if you aren't running ```mu-node-manage``` as **root**
