### ISSUE TITLE
Mu BOK deployment failing in same VPC

### ISSUE THREAD

**Issue by cgswong** [cloudamatic/mu#53]
I have successfully deployed Mu Master in US-WEST-2 using CentOS 6 AMI from the image listing to the public subnet in my VPC. When I try and do a deployment into a private subnet (same VPC as Mu Master) it fails on the configuration part, even though I can SSH after the fact into the instance from the Mu Master, and have internet access from the instance:
```
$ mu-deploy -n -e dev -p vpc_id=vpc-6625c501  /opt/mu/var/geospatial-platform/applications/proxy.yaml | tee -a /tmp/mu-deploy.log
Oct 23 19:20:20 - /opt/mu/lib/modules/mu - PROXY-DEV-2016102319-SP-PROXY-RX3 is in a private subnet (Subnet 'PROXY-DEV-2016102319-SP-VPC-6625C501-172_16_1_64_26' (subnet-e830109e)), but has no NAT host configured, and I have no other route to it
Oct 23 19:20:20 - deploy - MU::MuError
    {
  "thread": 40264000,
  "name": "server_pool_proxy_create",
  "details": [
    "/opt/mu/lib/modules/mu/clouds/aws/server.rb:846:in `postBoot'",
    "/opt/mu/lib/modules/mu/cloud.rb:958:in `call'",
    "/opt/mu/lib/modules/mu/cloud.rb:958:in `block (4 levels) in <class:Cloud>'",
    "/opt/mu/lib/modules/mu/clouds/aws/server_pool.rb:420:in `block (2 levels) in create'"
  ]
}
Oct 23 19:20:20 - /opt/mu/lib/modules/mu -
    {
  "thread": 40264000,
  "name": "server_pool_proxy_create"
}
Oct 23 19:20:20 - deploy - MU::MuError
    {
  "thread": 11326420,
  "name": "main_thread",
  "details": [
    "/opt/mu/lib/modules/mu/clouds/aws/server.rb:846:in `postBoot'",
    "/opt/mu/lib/modules/mu/cloud.rb:958:in `call'",
    "/opt/mu/lib/modules/mu/cloud.rb:958:in `block (4 levels) in <class:Cloud>'",
    "/opt/mu/lib/modules/mu/clouds/aws/server_pool.rb:420:in `block (2 levels) in create'"
  ]
}
```

Any thoughts on this strange behavior?

**Comment by rpattcorner** [comment]
We've talked things over and suspect that there may be no route from the public (master resident) subnet to the private (node resident) subnets.  This would especially make sense if the VPC was created manually.  Can you have a look at your VPC routing tables and let us know?

**Comment by cgswong** [comment]
I had a similar though, however, the public, private and main route tables include the VPC CIDR block as destination routes. Also, I can SSH from the Mu Master to the deployed (but not configured) instance which means there is a route. So unless I am mistaken the route setup looks fine.

**Comment by cgswong** [comment]
Closing this issue as it has been addressed by patch, https://github.com/cloudamatic/mu/commit/a0a90d66eb27d9549e7a998b6b5eacb4f832277d

Turns out deploying in the same VPC was not part of the code, at least not in the `min` branch, strange.
