### ISSUE TITLE
Final generic firewall update doesn't respect prior settings

### ISSUE THREAD

**Issue by rpattcorner** [cloudamatic/mu#64]
After the user specified recipes finish running, Momma-cat seems to run a series of additional recipes from mu.  One of them adjusts the firewall, but in six-pack-albs doesn't successfully clone the rules from the preexisting IPTables.

Chef gives a warning that cloning might not work now and requires unique names ... with this reference:
```[2017-04-10T07:51:24-04:00] WARN: Cloning resource attributes for service[iptables] from prior resource
Previous service[iptables]: /var/chef/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:52:in `block (3 levels) in <class:FirewallIptables>'
Current  service[iptables]: /var/chef/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:111:in `block (2 levels) in <class:FirewallIptables>' (CHEF-3694)/var/chef/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:111:in `block (2 levels) in <class:FirewallIptables>'.
Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
```

The resulting firewall doesn't have the rules from the former firewall -- in this case the 8080 pass rule

**Comment by jstange** [comment]
Per phone, this doesn't have anything to do with Momma Cat. It's gonna be pure Chef.

Your warning there suggests that this is entirely internal to the `firewall` community cookbook. But that's the warning you pasted, which may or may not have anything to do with the firewall overwriting behavior that you described, which is an actual problem. Be prepared for the possibility that the warning is irrelevant, as you investigate.
