### ISSUE TITLE
Don't let localhost sneak into mu.yaml

### ISSUE THREAD

**Issue by agill17** [cloudamatic/mu#80]
As per the wiki documentation on how to install a mu-master from scratch, there is a step which states "For simplicity, leave the other parameters alone for now. Any of these parameters can be changed after install by rerunning the script.
Enter “O” to start the install. The install takes about 35 minutes: InstallHome". By typing "O" , the installer assigns localhost address to public_address(Chef server address) in /opt/mu/etc/mu.yaml. Therefore the knife bootstrap fails when running a BOK.

**Comment by jstange** [comment]
Possibly addressed in 96c2054616e6a59bf0c99a8c69a69cc044a6e109. Previously `mu-configure` would only validate when a user input a value. Now it will also validate when reading in configuration from disk, and when you attempt to commit a config. In the latter case, it will exit if you've left anything naughty in place.

I'm going to do a couple of master builds to make sure this doesn't trip up installs or anything.
