### ISSUE TITLE
init script funk on RHEL/CentOS 7

### ISSUE THREAD

**Issue by jstange** [cloudamatic/mu#82]
Nagios and 389DS are both known to behave badly, in the sense that issuing a service stop/start/restart does not work reliably. Further examination is needed to figure out the specifics.

Nagios' problem may have more to do with the community cookbook than the package itself.

**Comment by ryantiger658** [comment]
@jstange is the service named differently on CentOS 7? 

https://github.com/cloudamatic/mu/blob/0432671389f125fd2e8e6af7a548e485210ed2ec/cookbooks/mu-master/recipes/389ds.rb#L45

**Comment by ryantiger658** [comment]
the 389 service exists and can be started manually ie `service dirsrv@mu-master start` but for some reason chef is starting the service but not enabling it, even though it appears to be doing it [here](https://github.com/cloudamatic/mu/blob/0432671389f125fd2e8e6af7a548e485210ed2ec/cookbooks/mu-master/recipes/389ds.rb#L91).

Perhaps it has to do with the '@' in the name?
