### ISSUE TITLE
Incomplete Cleanups by Guesswork

### ISSUE THREAD

**Issue by rpattcorner** [cloudamatic/mu#86]
In winrm (and probably before) it looks like the guesswork mu-cleanup processes don't look in a few important places, like load balancers and target groups, and maybe even autoscale groups.  Less problems with cleanup from the deploy descriptor of course.

**Comment by jstange** [comment]
I've been doing a lot of these testing unrelated things, and haven't witnessed this behavior. You'll have to be more specific. The code for inspecting those places is present and runs normally under circumstances where I'd expect it to.
