### ISSUE TITLE
mu-self-update doesn't use chef node's run list

### ISSUE THREAD

**Issue by zr2d2** [cloudamatic/mu#87]
when running mu-self-update, calls to chef-client use a runlist override and ignore the local runlist

**Comment by jstange** [comment]
This code looks correct:

```
run_list = ["role[mu-master]"]
run_list << "role[mu-master-jenkins]" if $MU_CFG['jenkins']['enable']
run_list.concat($MU_CFG['master_runlist_extras']) if $MU_CFG['master_runlist_extras'].is_a?(Array)
```

...

```
MU.log "Running chef-client on MU-MASTER", MU::NOTICE
system("chef-client -o '#{run_list.join(",")}'")
```

I think the problem is that the extra run list entries aren't properly configured on the CBR Mu Master. Log into that guy and run `mu-configure`, and add the recipe/role/whatever using the `Mu Master Runlist Extras` menu option.
