### ISSUE TITLE
AWS: Lambda and GCP: Cloud Functions

### ISSUE THREAD

**Issue by jstange** [cloudamatic/mu#91]
We don't have a type for this right now on any provider. Open questions: what, exactly, would such a resource type do? Upload some code from a file?

**Comment by agill17** [comment]
So this resource should be able to create lambda functions with code entry from s3, inline or upload local zip file directly into a lambda function. It can also have the ability to attach triggers (API Gateway, cronjob from cloud watch, SNS notification), edit the default allocated memory of 128mb, attach execution roles, and add environment variables(which sometimes are referred to in an inline lambda function)
