### ISSUE TITLE
user-specific ssh keys, disabling of password auth

### ISSUE THREAD

**Issue by amatusko** [cloudamatic/mu#98]
CBR-DEV is password protected and does not use private keys. @jstange! :)  We need to right this travesty, disable passwords, and set up keys. I will do so manually for my user andrew.matusko.

**Comment by ryantiger658** [comment]
Is this a Mu issue, or an issue regarding a specific Mu Deployment?

**Comment by jstange** [comment]
It should be an enhancement for Mu generally. Ability to disable password auth on a master in favor of key-only, plus tooling to facilitate key handling in some way that's not manual.

**Comment by ryantiger658** [comment]
Thanks! I was just trying to figure out how to label the issue. Do we have any thoughts on how to automatically handle key auth? Should Mu generate the keys for the users?
